name: Sutka Monitor

on:
  schedule:
    - cron: "1-59/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: sutka-monitor
  cancel-in-progress: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync with remote (before generating files)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests matplotlib

      - name: Run script
        run: python sutka.py

      - name: Commit updated files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data.csv graf_*.png || true
          git commit -m "Update data and graph" || echo "Nothing to commit"

          git push
